[package]
name = "rustvox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.11.0"
glutin = "0.24"
glam = "0.19.0"
bytemuck = "1.7.2"
crossbeam = "0.8.1"
crossbeam-channel = "0.5.1"
